INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Kabul','af','Asia','flags/1x1/af.svg','flags/4x3/af.svg',True,'Afghanistan'),
	 ('Mariehamn','ax','Europe','flags/1x1/ax.svg','flags/4x3/ax.svg',True,'Aland Islands'),
	 ('Tirana','al','Europe','flags/1x1/al.svg','flags/4x3/al.svg',True,'Albania'),
	 ('Algiers','dz','Africa','flags/1x1/dz.svg','flags/4x3/dz.svg',True,'Algeria'),
	 ('Pago Pago','as','Oceania','flags/1x1/as.svg','flags/4x3/as.svg',True,'American Samoa'),
	 ('Andorra la Vella','ad','Europe','flags/1x1/ad.svg','flags/4x3/ad.svg',True,'Andorra'),
	 ('Luanda','ao','Africa','flags/1x1/ao.svg','flags/4x3/ao.svg',True,'Angola'),
	 ('The Valley','ai','North America','flags/1x1/ai.svg','flags/4x3/ai.svg',True,'Anguilla'),
	 ('','aq','','flags/1x1/aq.svg','flags/4x3/aq.svg',True,' '),
	 ('St. John''s','ag','North America','flags/1x1/ag.svg','flags/4x3/ag.svg',True,'Antigua and Barbuda');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Buenos Aires','ar','South America','flags/1x1/ar.svg','flags/4x3/ar.svg',True,'Argentina'),
	 ('Yerevan','am','Asia','flags/1x1/am.svg','flags/4x3/am.svg',True,'Armenia'),
	 ('Oranjestad','aw','South America','flags/1x1/aw.svg','flags/4x3/aw.svg',True,'Aruba'),
	 ('Georgetown','sh-ac','Africa','flags/1x1/sh-ac.svg','flags/4x3/sh-ac.svg',False,'Ascension Island'),
	 ('Canberra','au','Oceania','flags/1x1/au.svg','flags/4x3/au.svg',True,'Australia'),
	 ('Vienna','at','Europe','flags/1x1/at.svg','flags/4x3/at.svg',True,'Austria'),
	 ('Baku','az','Asia','flags/1x1/az.svg','flags/4x3/az.svg',True,'Azerbaijan'),
	 ('Nassau','bs','North America','flags/1x1/bs.svg','flags/4x3/bs.svg',True,'Bahamas'),
	 ('Manama','bh','Asia','flags/1x1/bh.svg','flags/4x3/bh.svg',True,'Bahrain'),
	 ('Dhaka','bd','Asia','flags/1x1/bd.svg','flags/4x3/bd.svg',True,'Bangladesh');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Bridgetown','bb','North America','flags/1x1/bb.svg','flags/4x3/bb.svg',True,'Barbados'),
	 ('','es-pv','','flags/1x1/es-pv.svg','flags/4x3/es-pv.svg',False,'Basque Country'),
	 ('Minsk','by','Europe','flags/1x1/by.svg','flags/4x3/by.svg',True,'Belarus'),
	 ('Brussels','be','Europe','flags/1x1/be.svg','flags/4x3/be.svg',True,'Belgium'),
	 ('Belmopan','bz','North America','flags/1x1/bz.svg','flags/4x3/bz.svg',True,'Belize'),
	 ('Porto-Novo','bj','Africa','flags/1x1/bj.svg','flags/4x3/bj.svg',True,'Benin'),
	 ('Hamilton','bm','North America','flags/1x1/bm.svg','flags/4x3/bm.svg',True,'Bermuda'),
	 ('Thimphu','bt','Asia','flags/1x1/bt.svg','flags/4x3/bt.svg',True,'Bhutan'),
	 ('Sucre','bo','South America','flags/1x1/bo.svg','flags/4x3/bo.svg',True,'Bolivia'),
	 ('Kralendijk','bq','South America','flags/1x1/bq.svg','flags/4x3/bq.svg',True,'Bonaire, Sint Eustatius and Saba');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Sarajevo','ba','Europe','flags/1x1/ba.svg','flags/4x3/ba.svg',True,'Bosnia and Herzegovina'),
	 ('Gaborone','bw','Africa','flags/1x1/bw.svg','flags/4x3/bw.svg',True,'Botswana'),
	 ('','bv','','flags/1x1/bv.svg','flags/4x3/bv.svg',True,'Bouvet Island'),
	 ('Brasxedlia','br','South America','flags/1x1/br.svg','flags/4x3/br.svg',True,'Brazil'),
	 ('Diego Garcia','io','Asia','flags/1x1/io.svg','flags/4x3/io.svg',True,'British Indian Ocean Territory'),
	 ('Bandar Seri Begawan','bn','Asia','flags/1x1/bn.svg','flags/4x3/bn.svg',True,'Brunei Darussalam'),
	 ('Sofia','bg','Europe','flags/1x1/bg.svg','flags/4x3/bg.svg',True,'Bulgaria'),
	 ('Ouagadougou','bf','Africa','flags/1x1/bf.svg','flags/4x3/bf.svg',True,'Burkina Faso'),
	 ('Bujumbura','bi','Africa','flags/1x1/bi.svg','flags/4x3/bi.svg',True,'Burundi'),
	 ('Praia','cv','Africa','flags/1x1/cv.svg','flags/4x3/cv.svg',True,'Cabo Verde');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Phnom Penh','kh','Asia','flags/1x1/kh.svg','flags/4x3/kh.svg',True,'Cambodia'),
	 ('Yaoundxe9','cm','Africa','flags/1x1/cm.svg','flags/4x3/cm.svg',True,'Cameroon'),
	 ('Ottawa','ca','North America','flags/1x1/ca.svg','flags/4x3/ca.svg',True,'Canada'),
	 ('','ic','','flags/1x1/ic.svg','flags/4x3/ic.svg',False,'Canary Islands'),
	 ('','es-ct','','flags/1x1/es-ct.svg','flags/4x3/es-ct.svg',False,'Catalonia'),
	 ('George Town','ky','North America','flags/1x1/ky.svg','flags/4x3/ky.svg',True,'Cayman Islands'),
	 ('Bangui','cf','Africa','flags/1x1/cf.svg','flags/4x3/cf.svg',True,'Central African Republic'),
	 ('','cefta','','flags/1x1/cefta.svg','flags/4x3/cefta.svg',False,'Central European Free Trade Agreement'),
	 ('N''Djamena','td','Africa','flags/1x1/td.svg','flags/4x3/td.svg',True,'Chad'),
	 ('Santiago','cl','South America','flags/1x1/cl.svg','flags/4x3/cl.svg',True,'Chile');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Beijing','cn','Asia','flags/1x1/cn.svg','flags/4x3/cn.svg',True,'China'),
	 ('Flying Fish Cove','cx','Asia','flags/1x1/cx.svg','flags/4x3/cx.svg',True,'Christmas Island'),
	 ('','cp','','flags/1x1/cp.svg','flags/4x3/cp.svg',False,'Clipperton Island'),
	 ('West Island','cc','Asia','flags/1x1/cc.svg','flags/4x3/cc.svg',True,'Cocos (Keeling) Islands'),
	 ('Bogotxe1','co','South America','flags/1x1/co.svg','flags/4x3/co.svg',True,'Colombia'),
	 ('Moroni','km','Africa','flags/1x1/km.svg','flags/4x3/km.svg',True,'Comoros'),
	 ('Avarua','ck','Oceania','flags/1x1/ck.svg','flags/4x3/ck.svg',True,'Cook Islands'),
	 ('San Josxe9','cr','North America','flags/1x1/cr.svg','flags/4x3/cr.svg',True,'Costa Rica'),
	 ('Zagreb','hr','Europe','flags/1x1/hr.svg','flags/4x3/hr.svg',True,'Croatia'),
	 ('Havana','cu','North America','flags/1x1/cu.svg','flags/4x3/cu.svg',True,'Cuba');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Willemstad','cw','South America','flags/1x1/cw.svg','flags/4x3/cw.svg',True,'Curaxe7ao'),
	 ('Nicosia','cy','Europe','flags/1x1/cy.svg','flags/4x3/cy.svg',True,'Cyprus'),
	 ('Prague','cz','Europe','flags/1x1/cz.svg','flags/4x3/cz.svg',True,'Czech Republic'),
	 ('Yamoussoukro','ci','Africa','flags/1x1/ci.svg','flags/4x3/ci.svg',True,'Cxf4te d''Ivoire'),
	 ('Kinshasa','cd','Africa','flags/1x1/cd.svg','flags/4x3/cd.svg',True,'Democratic Republic of the Congo'),
	 ('Copenhagen','dk','Europe','flags/1x1/dk.svg','flags/4x3/dk.svg',True,'Denmark'),
	 ('','dg','','flags/1x1/dg.svg','flags/4x3/dg.svg',False,'Diego Garcia'),
	 ('Djibouti','dj','Africa','flags/1x1/dj.svg','flags/4x3/dj.svg',True,'Djibouti'),
	 ('Roseau','dm','North America','flags/1x1/dm.svg','flags/4x3/dm.svg',True,'Dominica'),
	 ('Santo Domingo','do','North America','flags/1x1/do.svg','flags/4x3/do.svg',True,'Dominican Republic');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('','eac','','flags/1x1/eac.svg','flags/4x3/eac.svg',False,'East African Community'),
	 ('Quito','ec','South America','flags/1x1/ec.svg','flags/4x3/ec.svg',True,'Ecuador'),
	 ('Cairo','eg','Africa','flags/1x1/eg.svg','flags/4x3/eg.svg',True,'Egypt'),
	 ('San Salvador','sv','North America','flags/1x1/sv.svg','flags/4x3/sv.svg',True,'El Salvador'),
	 ('London','gb-eng','Europe','flags/1x1/gb-eng.svg','flags/4x3/gb-eng.svg',False,'England'),
	 ('Malabo','gq','Africa','flags/1x1/gq.svg','flags/4x3/gq.svg',True,'Equatorial Guinea'),
	 ('Asmara','er','Africa','flags/1x1/er.svg','flags/4x3/er.svg',True,'Eritrea'),
	 ('Tallinn','ee','Europe','flags/1x1/ee.svg','flags/4x3/ee.svg',True,'Estonia'),
	 ('Lobamba, Mbabane','sz','Africa','flags/1x1/sz.svg','flags/4x3/sz.svg',True,'Eswatini'),
	 ('Addis Ababa','et','Africa','flags/1x1/et.svg','flags/4x3/et.svg',True,'Ethiopia');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('','eu','','flags/1x1/eu.svg','flags/4x3/eu.svg',False,'Europe'),
	 ('Stanley','fk','South America','flags/1x1/fk.svg','flags/4x3/fk.svg',True,'Falkland Islands'),
	 ('Txf3rshavn','fo','Europe','flags/1x1/fo.svg','flags/4x3/fo.svg',True,'Faroe Islands'),
	 ('Palikir','fm','Oceania','flags/1x1/fm.svg','flags/4x3/fm.svg',True,'Federated States of Micronesia'),
	 ('Suva','fj','Oceania','flags/1x1/fj.svg','flags/4x3/fj.svg',True,'Fiji'),
	 ('Helsinki','fi','Europe','flags/1x1/fi.svg','flags/4x3/fi.svg',True,'Finland'),
	 ('Paris','fr','Europe','flags/1x1/fr.svg','flags/4x3/fr.svg',True,'France'),
	 ('Cayenne','gf','South America','flags/1x1/gf.svg','flags/4x3/gf.svg',True,'French Guiana'),
	 ('Papeete','pf','Oceania','flags/1x1/pf.svg','flags/4x3/pf.svg',True,'French Polynesia'),
	 ('Saint-Pierre, Rxe9union','tf','Africa','flags/1x1/tf.svg','flags/4x3/tf.svg',True,'French Southern Territories');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Libreville','ga','Africa','flags/1x1/ga.svg','flags/4x3/ga.svg',True,'Gabon'),
	 ('','es-ga','','flags/1x1/es-ga.svg','flags/4x3/es-ga.svg',False,'Galicia'),
	 ('Banjul','gm','Africa','flags/1x1/gm.svg','flags/4x3/gm.svg',True,'Gambia'),
	 ('Tbilisi','ge','Asia','flags/1x1/ge.svg','flags/4x3/ge.svg',True,'Georgia'),
	 ('Berlin','de','Europe','flags/1x1/de.svg','flags/4x3/de.svg',True,'Germany'),
	 ('Accra','gh','Africa','flags/1x1/gh.svg','flags/4x3/gh.svg',True,'Ghana'),
	 ('Gibraltar','gi','Europe','flags/1x1/gi.svg','flags/4x3/gi.svg',True,'Gibraltar'),
	 ('Athens','gr','Europe','flags/1x1/gr.svg','flags/4x3/gr.svg',True,'Greece'),
	 ('Nuuk','gl','North America','flags/1x1/gl.svg','flags/4x3/gl.svg',True,'Greenland'),
	 ('St. George''s','gd','North America','flags/1x1/gd.svg','flags/4x3/gd.svg',True,'Grenada');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Basse-Terre','gp','North America','flags/1x1/gp.svg','flags/4x3/gp.svg',True,'Guadeloupe'),
	 ('Hagxe5txf1a','gu','Oceania','flags/1x1/gu.svg','flags/4x3/gu.svg',True,'Guam'),
	 ('Guatemala City','gt','North America','flags/1x1/gt.svg','flags/4x3/gt.svg',True,'Guatemala'),
	 ('Saint Peter Port','gg','Europe','flags/1x1/gg.svg','flags/4x3/gg.svg',True,'Guernsey'),
	 ('Conakry','gn','Africa','flags/1x1/gn.svg','flags/4x3/gn.svg',True,'Guinea'),
	 ('Bissau','gw','Africa','flags/1x1/gw.svg','flags/4x3/gw.svg',True,'Guinea-Bissau'),
	 ('Georgetown','gy','South America','flags/1x1/gy.svg','flags/4x3/gy.svg',True,'Guyana'),
	 ('Port-au-Prince','ht','North America','flags/1x1/ht.svg','flags/4x3/ht.svg',True,'Haiti'),
	 ('','hm','','flags/1x1/hm.svg','flags/4x3/hm.svg',True,'Heard Island and McDonald Islands'),
	 ('Vatican City','va','Europe','flags/1x1/va.svg','flags/4x3/va.svg',True,'Holy See');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Tegucigalpa','hn','North America','flags/1x1/hn.svg','flags/4x3/hn.svg',True,'Honduras'),
	 ('Hong Kong','hk','Asia','flags/1x1/hk.svg','flags/4x3/hk.svg',True,'Hong Kong'),
	 ('Budapest','hu','Europe','flags/1x1/hu.svg','flags/4x3/hu.svg',True,'Hungary'),
	 ('Reykjavik','is','Europe','flags/1x1/is.svg','flags/4x3/is.svg',True,'Iceland'),
	 ('New Delhi','in','Asia','flags/1x1/in.svg','flags/4x3/in.svg',True,'India'),
	 ('Jakarta','id','Asia','flags/1x1/id.svg','flags/4x3/id.svg',True,'Indonesia'),
	 ('Tehran','ir','Asia','flags/1x1/ir.svg','flags/4x3/ir.svg',True,'Iran'),
	 ('Baghdad','iq','Asia','flags/1x1/iq.svg','flags/4x3/iq.svg',True,'Iraq'),
	 ('Dublin','ie','Europe','flags/1x1/ie.svg','flags/4x3/ie.svg',True,'Ireland'),
	 ('Douglas','im','Europe','flags/1x1/im.svg','flags/4x3/im.svg',True,'Isle of Man');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Jerusalem','il','Asia','flags/1x1/il.svg','flags/4x3/il.svg',True,'Israel'),
	 ('Rome','it','Europe','flags/1x1/it.svg','flags/4x3/it.svg',True,'Italy'),
	 ('Kingston','jm','North America','flags/1x1/jm.svg','flags/4x3/jm.svg',True,'Jamaica'),
	 ('Tokyo','jp','Asia','flags/1x1/jp.svg','flags/4x3/jp.svg',True,'Japan'),
	 ('Saint Helier','je','Europe','flags/1x1/je.svg','flags/4x3/je.svg',True,'Jersey'),
	 ('Amman','jo','Asia','flags/1x1/jo.svg','flags/4x3/jo.svg',True,'Jordan'),
	 ('Astana','kz','Asia','flags/1x1/kz.svg','flags/4x3/kz.svg',True,'Kazakhstan'),
	 ('Nairobi','ke','Africa','flags/1x1/ke.svg','flags/4x3/ke.svg',True,'Kenya'),
	 ('South Tarawa','ki','Oceania','flags/1x1/ki.svg','flags/4x3/ki.svg',True,'Kiribati'),
	 ('Pristina','xk','Europe','flags/1x1/xk.svg','flags/4x3/xk.svg',False,'Kosovo');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Kuwait City','kw','Asia','flags/1x1/kw.svg','flags/4x3/kw.svg',True,'Kuwait'),
	 ('Bishkek','kg','Asia','flags/1x1/kg.svg','flags/4x3/kg.svg',True,'Kyrgyzstan'),
	 ('Vientiane','la','Asia','flags/1x1/la.svg','flags/4x3/la.svg',True,'Laos'),
	 ('Riga','lv','Europe','flags/1x1/lv.svg','flags/4x3/lv.svg',True,'Latvia'),
	 ('','arab','','flags/1x1/arab.svg','flags/4x3/arab.svg',False,'League of Arab States'),
	 ('Beirut','lb','Asia','flags/1x1/lb.svg','flags/4x3/lb.svg',True,'Lebanon'),
	 ('Maseru','ls','Africa','flags/1x1/ls.svg','flags/4x3/ls.svg',True,'Lesotho'),
	 ('Monrovia','lr','Africa','flags/1x1/lr.svg','flags/4x3/lr.svg',True,'Liberia'),
	 ('Tripoli','ly','Africa','flags/1x1/ly.svg','flags/4x3/ly.svg',True,'Libya'),
	 ('Vaduz','li','Europe','flags/1x1/li.svg','flags/4x3/li.svg',True,'Liechtenstein');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Vilnius','lt','Europe','flags/1x1/lt.svg','flags/4x3/lt.svg',True,'Lithuania'),
	 ('Luxembourg City','lu','Europe','flags/1x1/lu.svg','flags/4x3/lu.svg',True,'Luxembourg'),
	 ('Macau','mo','Asia','flags/1x1/mo.svg','flags/4x3/mo.svg',True,'Macau'),
	 ('Antananarivo','mg','Africa','flags/1x1/mg.svg','flags/4x3/mg.svg',True,'Madagascar'),
	 ('Lilongwe','mw','Africa','flags/1x1/mw.svg','flags/4x3/mw.svg',True,'Malawi'),
	 ('Kuala Lumpur','my','Asia','flags/1x1/my.svg','flags/4x3/my.svg',True,'Malaysia'),
	 ('Malxe9','mv','Asia','flags/1x1/mv.svg','flags/4x3/mv.svg',True,'Maldives'),
	 ('Bamako','ml','Africa','flags/1x1/ml.svg','flags/4x3/ml.svg',True,'Mali'),
	 ('Valletta','mt','Europe','flags/1x1/mt.svg','flags/4x3/mt.svg',True,'Malta'),
	 ('Majuro','mh','Oceania','flags/1x1/mh.svg','flags/4x3/mh.svg',True,'Marshall Islands');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Fort-de-France','mq','North America','flags/1x1/mq.svg','flags/4x3/mq.svg',True,'Martinique'),
	 ('Nouakchott','mr','Africa','flags/1x1/mr.svg','flags/4x3/mr.svg',True,'Mauritania'),
	 ('Port Louis','mu','Africa','flags/1x1/mu.svg','flags/4x3/mu.svg',True,'Mauritius'),
	 ('Mamoudzou','yt','Africa','flags/1x1/yt.svg','flags/4x3/yt.svg',True,'Mayotte'),
	 ('Mexico City','mx','North America','flags/1x1/mx.svg','flags/4x3/mx.svg',True,'Mexico'),
	 ('Chiu0219inu0103u','md','Europe','flags/1x1/md.svg','flags/4x3/md.svg',True,'Moldova'),
	 ('Monaco','mc','Europe','flags/1x1/mc.svg','flags/4x3/mc.svg',True,'Monaco'),
	 ('Ulaanbaatar','mn','Asia','flags/1x1/mn.svg','flags/4x3/mn.svg',True,'Mongolia'),
	 ('Podgorica','me','Europe','flags/1x1/me.svg','flags/4x3/me.svg',True,'Montenegro'),
	 ('Little Bay, Brades, Plymouth','ms','North America','flags/1x1/ms.svg','flags/4x3/ms.svg',True,'Montserrat');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Rabat','ma','Africa','flags/1x1/ma.svg','flags/4x3/ma.svg',True,'Morocco'),
	 ('Maputo','mz','Africa','flags/1x1/mz.svg','flags/4x3/mz.svg',True,'Mozambique'),
	 ('Naypyidaw','mm','Asia','flags/1x1/mm.svg','flags/4x3/mm.svg',True,'Myanmar'),
	 ('Windhoek','na','Africa','flags/1x1/na.svg','flags/4x3/na.svg',True,'Namibia'),
	 ('Yaren District','nr','Oceania','flags/1x1/nr.svg','flags/4x3/nr.svg',True,'Nauru'),
	 ('Kathmandu','np','Asia','flags/1x1/np.svg','flags/4x3/np.svg',True,'Nepal'),
	 ('Amsterdam','nl','Europe','flags/1x1/nl.svg','flags/4x3/nl.svg',True,'Netherlands'),
	 ('Noumxe9a','nc','Oceania','flags/1x1/nc.svg','flags/4x3/nc.svg',True,'New Caledonia'),
	 ('Wellington','nz','Oceania','flags/1x1/nz.svg','flags/4x3/nz.svg',True,'New Zealand'),
	 ('Managua','ni','North America','flags/1x1/ni.svg','flags/4x3/ni.svg',True,'Nicaragua');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Niamey','ne','Africa','flags/1x1/ne.svg','flags/4x3/ne.svg',True,'Niger'),
	 ('Abuja','ng','Africa','flags/1x1/ng.svg','flags/4x3/ng.svg',True,'Nigeria'),
	 ('Alofi','nu','Oceania','flags/1x1/nu.svg','flags/4x3/nu.svg',True,'Niue'),
	 ('Kingston','nf','Oceania','flags/1x1/nf.svg','flags/4x3/nf.svg',True,'Norfolk Island'),
	 ('Pyongyang','kp','Asia','flags/1x1/kp.svg','flags/4x3/kp.svg',True,'North Korea'),
	 ('Skopje','mk','Europe','flags/1x1/mk.svg','flags/4x3/mk.svg',True,'North Macedonia'),
	 ('Belfast','gb-nir','Europe','flags/1x1/gb-nir.svg','flags/4x3/gb-nir.svg',False,'Northern Ireland'),
	 ('Saipan','mp','Oceania','flags/1x1/mp.svg','flags/4x3/mp.svg',True,'Northern Mariana Islands'),
	 ('Oslo','no','Europe','flags/1x1/no.svg','flags/4x3/no.svg',True,'Norway'),
	 ('Muscat','om','Asia','flags/1x1/om.svg','flags/4x3/om.svg',True,'Oman');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('','pc','','flags/1x1/pc.svg','flags/4x3/pc.svg',False,'Pacific Community'),
	 ('Islamabad','pk','Asia','flags/1x1/pk.svg','flags/4x3/pk.svg',True,'Pakistan'),
	 ('Ngerulmud','pw','Oceania','flags/1x1/pw.svg','flags/4x3/pw.svg',True,'Palau'),
	 ('Panama City','pa','North America','flags/1x1/pa.svg','flags/4x3/pa.svg',True,'Panama'),
	 ('Port Moresby','pg','Oceania','flags/1x1/pg.svg','flags/4x3/pg.svg',True,'Papua New Guinea'),
	 ('Asuncixf3n','py','South America','flags/1x1/py.svg','flags/4x3/py.svg',True,'Paraguay'),
	 ('Lima','pe','South America','flags/1x1/pe.svg','flags/4x3/pe.svg',True,'Peru'),
	 ('Manila','ph','Asia','flags/1x1/ph.svg','flags/4x3/ph.svg',True,'Philippines'),
	 ('Adamstown','pn','Oceania','flags/1x1/pn.svg','flags/4x3/pn.svg',True,'Pitcairn'),
	 ('Warsaw','pl','Europe','flags/1x1/pl.svg','flags/4x3/pl.svg',True,'Poland');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Lisbon','pt','Europe','flags/1x1/pt.svg','flags/4x3/pt.svg',True,'Portugal'),
	 ('San Juan','pr','North America','flags/1x1/pr.svg','flags/4x3/pr.svg',True,'Puerto Rico'),
	 ('Doha','qa','Asia','flags/1x1/qa.svg','flags/4x3/qa.svg',True,'Qatar'),
	 ('Brazzaville','cg','Africa','flags/1x1/cg.svg','flags/4x3/cg.svg',True,'Republic of the Congo'),
	 ('Bucharest','ro','Europe','flags/1x1/ro.svg','flags/4x3/ro.svg',True,'Romania'),
	 ('Moscow','ru','Europe','flags/1x1/ru.svg','flags/4x3/ru.svg',True,'Russia'),
	 ('Kigali','rw','Africa','flags/1x1/rw.svg','flags/4x3/rw.svg',True,'Rwanda'),
	 ('Saint-Denis','re','Africa','flags/1x1/re.svg','flags/4x3/re.svg',True,'Rxe9union'),
	 ('Gustavia','bl','North America','flags/1x1/bl.svg','flags/4x3/bl.svg',True,'Saint Barthxe9lemy'),
	 ('Jamestown','sh-hl','Africa','flags/1x1/sh-hl.svg','flags/4x3/sh-hl.svg',False,'Saint Helena');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Jamestown','sh','Africa','flags/1x1/sh.svg','flags/4x3/sh.svg',True,'Saint Helena, Ascension and Tristan da Cunha'),
	 ('Basseterre','kn','North America','flags/1x1/kn.svg','flags/4x3/kn.svg',True,'Saint Kitts and Nevis'),
	 ('Castries','lc','North America','flags/1x1/lc.svg','flags/4x3/lc.svg',True,'Saint Lucia'),
	 ('Marigot','mf','North America','flags/1x1/mf.svg','flags/4x3/mf.svg',True,'Saint Martin'),
	 ('Saint-Pierre','pm','North America','flags/1x1/pm.svg','flags/4x3/pm.svg',True,'Saint Pierre and Miquelon'),
	 ('Kingstown','vc','North America','flags/1x1/vc.svg','flags/4x3/vc.svg',True,'Saint Vincent and the Grenadines'),
	 ('Apia','ws','Oceania','flags/1x1/ws.svg','flags/4x3/ws.svg',True,'Samoa'),
	 ('San Marino','sm','Europe','flags/1x1/sm.svg','flags/4x3/sm.svg',True,'San Marino'),
	 ('Sxe3o Tomxe9','st','Africa','flags/1x1/st.svg','flags/4x3/st.svg',True,'Sao Tome and Principe'),
	 ('Riyadh','sa','Asia','flags/1x1/sa.svg','flags/4x3/sa.svg',True,'Saudi Arabia');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Edinburgh','gb-sct','Europe','flags/1x1/gb-sct.svg','flags/4x3/gb-sct.svg',False,'Scotland'),
	 ('Dakar','sn','Africa','flags/1x1/sn.svg','flags/4x3/sn.svg',True,'Senegal'),
	 ('Belgrade','rs','Europe','flags/1x1/rs.svg','flags/4x3/rs.svg',True,'Serbia'),
	 ('Victoria','sc','Africa','flags/1x1/sc.svg','flags/4x3/sc.svg',True,'Seychelles'),
	 ('Freetown','sl','Africa','flags/1x1/sl.svg','flags/4x3/sl.svg',True,'Sierra Leone'),
	 ('Singapore','sg','Asia','flags/1x1/sg.svg','flags/4x3/sg.svg',True,'Singapore'),
	 ('Philipsburg','sx','North America','flags/1x1/sx.svg','flags/4x3/sx.svg',True,'Sint Maarten'),
	 ('Bratislava','sk','Europe','flags/1x1/sk.svg','flags/4x3/sk.svg',True,'Slovakia'),
	 ('Ljubljana','si','Europe','flags/1x1/si.svg','flags/4x3/si.svg',True,'Slovenia'),
	 ('Honiara','sb','Oceania','flags/1x1/sb.svg','flags/4x3/sb.svg',True,'Solomon Islands');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Mogadishu','so','Africa','flags/1x1/so.svg','flags/4x3/so.svg',True,'Somalia'),
	 ('Pretoria','za','Africa','flags/1x1/za.svg','flags/4x3/za.svg',True,'South Africa'),
	 ('King Edward Point','gs','Antarctica','flags/1x1/gs.svg','flags/4x3/gs.svg',True,'South Georgia and the South Sandwich Islands'),
	 ('Seoul','kr','Asia','flags/1x1/kr.svg','flags/4x3/kr.svg',True,'South Korea'),
	 ('Juba','ss','Africa','flags/1x1/ss.svg','flags/4x3/ss.svg',True,'South Sudan'),
	 ('Madrid','es','Europe','flags/1x1/es.svg','flags/4x3/es.svg',True,'Spain'),
	 ('Sri Jayawardenepura Kotte, Colombo','lk','Asia','flags/1x1/lk.svg','flags/4x3/lk.svg',True,'Sri Lanka'),
	 ('Ramallah','ps','Asia','flags/1x1/ps.svg','flags/4x3/ps.svg',True,'State of Palestine'),
	 ('Khartoum','sd','Africa','flags/1x1/sd.svg','flags/4x3/sd.svg',True,'Sudan'),
	 ('Paramaribo','sr','South America','flags/1x1/sr.svg','flags/4x3/sr.svg',True,'Suriname');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Longyearbyen','sj','Europe','flags/1x1/sj.svg','flags/4x3/sj.svg',True,'Svalbard and Jan Mayen'),
	 ('Stockholm','se','Europe','flags/1x1/se.svg','flags/4x3/se.svg',True,'Sweden'),
	 ('Bern','ch','Europe','flags/1x1/ch.svg','flags/4x3/ch.svg',True,'Switzerland'),
	 ('Damascus','sy','Asia','flags/1x1/sy.svg','flags/4x3/sy.svg',True,'Syria'),
	 ('Taipei','tw','Asia','flags/1x1/tw.svg','flags/4x3/tw.svg',True,'Taiwan'),
	 ('Dushanbe','tj','Asia','flags/1x1/tj.svg','flags/4x3/tj.svg',True,'Tajikistan'),
	 ('Dodoma','tz','Africa','flags/1x1/tz.svg','flags/4x3/tz.svg',True,'Tanzania'),
	 ('Bangkok','th','Asia','flags/1x1/th.svg','flags/4x3/th.svg',True,'Thailand'),
	 ('Dili','tl','Asia','flags/1x1/tl.svg','flags/4x3/tl.svg',True,'Timor-Leste'),
	 ('Lomxe9','tg','Africa','flags/1x1/tg.svg','flags/4x3/tg.svg',True,'Togo');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Nukunonu, Atafu,Tokelau','tk','Oceania','flags/1x1/tk.svg','flags/4x3/tk.svg',True,'Tokelau'),
	 ('Nukuu02bbalofa','to','Oceania','flags/1x1/to.svg','flags/4x3/to.svg',True,'Tonga'),
	 ('Port of Spain','tt','South America','flags/1x1/tt.svg','flags/4x3/tt.svg',True,'Trinidad and Tobago'),
	 ('Edinburgh of the Seven Seas','sh-ta','Africa','flags/1x1/sh-ta.svg','flags/4x3/sh-ta.svg',False,'Tristan da Cunha'),
	 ('Tunis','tn','Africa','flags/1x1/tn.svg','flags/4x3/tn.svg',True,'Tunisia'),
	 ('Ashgabat','tm','Asia','flags/1x1/tm.svg','flags/4x3/tm.svg',True,'Turkmenistan'),
	 ('Cockburn Town','tc','North America','flags/1x1/tc.svg','flags/4x3/tc.svg',True,'Turks and Caicos Islands'),
	 ('Funafuti','tv','Oceania','flags/1x1/tv.svg','flags/4x3/tv.svg',True,'Tuvalu'),
	 ('Ankara','tr','Asia','flags/1x1/tr.svg','flags/4x3/tr.svg',True,'Txfcrkiye'),
	 ('Kampala','ug','Africa','flags/1x1/ug.svg','flags/4x3/ug.svg',True,'Uganda');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Kiev','ua','Europe','flags/1x1/ua.svg','flags/4x3/ua.svg',True,'Ukraine'),
	 ('Abu Dhabi','ae','Asia','flags/1x1/ae.svg','flags/4x3/ae.svg',True,'United Arab Emirates'),
	 ('London','gb','Europe','flags/1x1/gb.svg','flags/4x3/gb.svg',True,'United Kingdom'),
	 ('','un','','flags/1x1/un.svg','flags/4x3/un.svg',False,'United Nations'),
	 ('Washington, D.C.','um','North America','flags/1x1/um.svg','flags/4x3/um.svg',True,'United States Minor Outlying Islands'),
	 ('Washington, D.C.','us','North America','flags/1x1/us.svg','flags/4x3/us.svg',True,'United States of America'),
	 ('','xx','','flags/1x1/xx.svg','flags/4x3/xx.svg',False,'Unknown'),
	 ('Montevideo','uy','South America','flags/1x1/uy.svg','flags/4x3/uy.svg',True,'Uruguay'),
	 ('Tashkent','uz','Asia','flags/1x1/uz.svg','flags/4x3/uz.svg',True,'Uzbekistan'),
	 ('Port Vila','vu','Oceania','flags/1x1/vu.svg','flags/4x3/vu.svg',True,'Vanuatu');
INSERT INTO country (capital,code,continent,flag_1x1,flag_4x3,iso,name) VALUES
	 ('Caracas','ve','South America','flags/1x1/ve.svg','flags/4x3/ve.svg',True,'Venezuela'),
	 ('Hanoi','vn','Asia','flags/1x1/vn.svg','flags/4x3/vn.svg',True,'Vietnam'),
	 ('Road Town','vg','North America','flags/1x1/vg.svg','flags/4x3/vg.svg',True,'Virgin Islands (British)'),
	 ('Charlotte Amalie','vi','North America','flags/1x1/vi.svg','flags/4x3/vi.svg',True,'Virgin Islands (U.S.)'),
	 ('Cardiff','gb-wls','Europe','flags/1x1/gb-wls.svg','flags/4x3/gb-wls.svg',False,'Wales'),
	 ('Mata-Utu','wf','Oceania','flags/1x1/wf.svg','flags/4x3/wf.svg',True,'Wallis and Futuna'),
	 ('Laayoune','eh','Africa','flags/1x1/eh.svg','flags/4x3/eh.svg',True,'Western Sahara'),
	 ('Sana''a','ye','Asia','flags/1x1/ye.svg','flags/4x3/ye.svg',True,'Yemen'),
	 ('Lusaka','zm','Africa','flags/1x1/zm.svg','flags/4x3/zm.svg',True,'Zambia'),
	 ('Harare','zw','Africa','flags/1x1/zw.svg','flags/4x3/zw.svg',True,'Zimbabwe');
